name: release

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    # runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: 展示版本
        run: echo ${{ steps.get_version.outputs.VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 打包镜像并推送
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            VAN_BLOG_VERSIONS=${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            "docker.io/duhbbx/vanblog:${{ steps.get_version.outputs.VERSION }}"
            "docker.io/duhbbx/vanblog:latest"
